---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      command: "docker stop raam043/test_project:latest"
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/test_project:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
