---
- hosts: rnb
  become: True
  tasks:
        
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/test_project:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
   
   - name: Rename the container
     command: "docker rename raam043/test_project:latest raam043/test_project:v2"
