---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      command: "subscription-manager repos --enable rhel-server-rhscl-7-rpms"
      command: "yum -y install rh-python36"
      command: "scl enable rh-python36 bash"
      command: "pip3 install --upgrade pip"


      
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/test_project:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
