---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      command: "subscription-manager repos --enable rhel-server-rhscl-7-rpms"
      command: "yum install python27-python-pip -y"
      command: "scl enable python27 bash"
      command: "pip install --upgrade pip"


      
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/test_project:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
