---
- hosts: rnb
  become: True
  tasks:
  
    - name: Delete old images
      command: "docker stop raam043/nginx_project:latest"
      command: "docker rm -f raam043/nginx_project:latest"
      command: "docker image rm -f raam043/nginx_project:latest"
      
    - name: Pull nginx docker image
      docker_image:
        name: nginx
        tag: latest
        source: pull
    - name: Copy website to the host
      copy:
        src: ./index.html
        dest: /usr/share/nginx/html/
      
    - name: docker rename
      command: "docker tag nginx:latest raam043/nginx_project:latest"
