---
- hosts: rnb
  become: True
  tasks:
  
    - name: Pull nginx docker image
      docker_image:
        name: nginx
        tag: latest
        source: pull
    - name: Copy website to the host
      command: "index.html /usr/share/nginx/html"
      
    - name: docker rename
      command: "docker tag nginx:latest raam043/nginx_project:latest"
