---
- hosts: rnb
  become: True
  tasks:
  
    - name: Delete old images
      command: "docker stop raam043/nginx_project"
      command: "docker rm -f raam043/nginx_project"
      command: "docker image rm -f raam043/nginx_project"
      
    - name: Pull nginx docker image
      docker_image:
        name: nginx
        tag: latest
        source: pull
    - name: Copy website to the host
      copy:
        src: index.html
        dest: /usr/share/nginx/html/
      
    - name: docker rename
      command: "docker tag nginx:latest raam043/nginx_project"
      command: "docker run -d --name raam043/nginx_project -p 80:80 raam043/nginx_project"
